apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: exec-tests-javascript-and-generate-report
  namespace: tekton-pipelines
spec:
  resources:
    - name: git-source
      type: git
  params:
    - name: BROWSER
    - name: TESTS_SUITE
  tasks:
    - name: task-exec-tests-javascript
      taskRef:
        name: task-exec-tests-javascript
      resources:
        inputs:
          - name: git-source
            resource: git-source
      params:
        - name: BROWSER
          value: $(params.BROWSER)
        - name: TESTS_SUITE
          value: $(params.TESTS_SUITE)
    - name: task-generate-report
      taskRef:
        name: task-generate-report
      runAfter:
        - task-exec-tests-javascript
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: exec-tests-python-and-generate-report
  namespace: tekton-pipelines
spec:
  resources:
    - name: git-source
      type: git
  params:
    - name: BROWSER
  tasks:
    - name: task-exec-tests-python
      taskRef:
        name: task-exec-tests-python
      resources:
        inputs:
          - name: git-source
            resource: git-source
      params:
        - name: BROWSER
          value: $(params.BROWSER)
    - name: task-generate-report
      taskRef:
        name: task-generate-report
      runAfter:
        - task-exec-tests-python
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: generate-report
  namespace: tekton-pipelines
spec:
  tasks:
    - name: task-generate-report
      taskRef:
        name: task-generate-report
