apiVersion: v1
kind: Secret
metadata:
  name: secret-auth-gitlab-javascript-tests
  namespace: tekton-pipelines
  annotations:
    tekton.dev/git-0: https://eu-de.git.cloud.ibm.com/poc-k8s-selenium/tests-javascript.git
type: kubernetes.io/basic-auth
stringData:
  password: 6yHrZh9FRsWnheh465WH
  username: token-jenkins
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-auth-gitlab-python-tests
  namespace: tekton-pipelines
  annotations:
    tekton.dev/git-1: https://eu-de.git.cloud.ibm.com/poc-k8s-selenium/tests-python.git
type: kubernetes.io/basic-auth
stringData:
  password: ETShePjruzo2ySNzPzrn
  username: token
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-pg-credentials
  namespace: tekton-pipelines
stringData:
  PG_USER: postgres
  PG_HOST: db-postgresql.default.svc.cluster.local
  PG_DATABASE: postgres
  PG_PASSWORD: CZQcniqo2h
  PG_PORT: "5432"
