apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-runner-test-executor
  namespace: tekton-pipelines
secrets:
  - name: secret-auth-gitlab-javascript-tests
  - name: secret-auth-gitlab-python-tests
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role-pipeline-run
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-pipeline-run
subjects:
  - kind: ServiceAccount
    name: pipeline-runner-test-executor
    namespace: tekton-pipelines
roleRef:
  kind: ClusterRole
  name: cluster-role-pipeline-run
  apiGroup: rbac.authorization.k8s.io
